config/routes.rb
Rails.application.routes.draw do

  get 'debug', to: 'debug#index'
  post 'debug', to: 'debug#add'
  get 'debug/delete/:id', to: 'debug#delete'
  post '/submit/analysis/:str', to: 'submit#handler'
  get '/submit/analyses/:id', to: 'submit#analyses'

  get '/index', to: 'welcome#index1'
  resources :projects do
    resources :samples do
      collection do
        post :import
        post :import_inf_table
      end
      member do
        post :upload_seq
        post :upload_inf
        get :download_seq
        get :download_inf
      end
    end
    collection { post :import}
    collection { post :download_selected_file }
    collection { post :export_selected }
    member { post :download_inf_table} 
  end

  resources :sections do
    post:import
    collection { post :export_selected }
    collection do
      post :make_selected_file
    end
  end

  resources :slices do
    post:import
    collection { post :export_selected }
    collection do
      post :make_selected_file
    end

  end

  resources :samples do
    post:import
    collection { post :export_selected }
    collection do
      post :make_selected_file
    end
  end

  resources :tissues do
    post:import
  end
  
  resources :species do
    post:import
  end

  resources :diseases do
    post:import
  end

  resources :organs do
    collection { post :import }
    collection { post :export_selected }
  end

  resources :cancers do
    collection { post :import }
    collection { post :export_selected }
  end

  resources :users do
    resources :datasets do
      member { post :upload_file }
      member { get :download_file}
      member { get :download_ds_inf}
      member { get :download_ds_metadata}
      member { post :delete_sample}
    end
  end
  
  root 'welcome#index'
  get 'tutorial', to: 'welcome#tutorial', as: 'tutorial'
  get '/tutorial/database/1', to: "tutorial#database1"
  get '/tutorial/database/2', to: "tutorial#database2"
  get '/tutorial/database/3', to: "tutorial#database3"
  get '/tutorial/database/4', to: "tutorial#database4"
  get '/tutorial/database/5', to: "tutorial#database5"
  get '/tutorial/database/6', to: "tutorial#database6"

  get '/tutorial/analysis/1', to: "tutorial#analysis1"
  get '/tutorial/analysis/2', to: "tutorial#analysis2"
  get '/tutorial/analysis/3', to: "tutorial#analysis3"
  get '/tutorial/analysis/4', to: "tutorial#analysis4"

  get 'docs', to: redirect('docs/index.html')
  get 'contact', to: 'welcome#contact', as: 'contact'
  get 'terms', to: 'welcome#terms', as: 'terms'

  # read local csv file 
  # get 'data/:name', to: 'raw_files#index'
  get 'api/local', to: 'raw_files#index'
  get 'api/public', to: 'raw_files#public'

  # draw on overview page
  namespace :api do
    resources :analysis, only: [] do
      get 'use_demo', to: 'viz_files#use_demo', as: 'use_demo'
      get 'use_task_output', to: 'viz_files#use_task_output', as: 'use_task_output'
      get 'all_files', to: 'viz_files#all_files', as: 'all_files'
      get 'all_task_outputs', to: 'viz_files#all_task_outputs', as: 'all_task_outputs'
      get 'chosen_files', to: 'viz_files#get_chosen_files', as: 'chosen_files'
      get 'chosen_file_paths', to: 'viz_files#chosen_file_paths', as: 'chosen_file_paths'
      get 'download_demo_file', to: 'viz_files#download_demo_file', as: 'download_demo_file'
      post 'chosen_files', to: 'viz_files#update_chosen_files', as: 'update_chosen_files'
      post 'create_files', to: 'viz_files#create_files', as: 'create_files'
      post 'batch_delete_files', to: 'viz_files#batch_delete_files', as: 'batch_delete_files'
    end
    get "public_file/check_file_exists", to: 'public_file#check_file_exists', as: 'json'
    get 'tabix/:url_name', to: 'tabix_apis#show', as: 'tabix_api'
    get 'public/:url_name', to: 'public_file_apis#show', as: 'public_api'
  end

  # database pages
  get 'database/overview', to: 'database#overview'
  get '/download', to: 'welcome#download'

  get 'user/show', to: 'users#show'
  # get 'demo', to: 'demo#show'
  #post 'welcome/accept_cookies', to: 'welcome#require_cookie'
  post "welcome/require_cookie", to: "welcome#require_cookie", as: "require_cookie"
  
  # visualizer
  scope '/visualizer' do
    # resources :analysis, except: :index
    get 'analysis/:url_name', to: 'analysis#show', as: 'analysis'
  end
  get 'visualizer', to: "analysis#index", as: "visualizer"


  # submit pages
  get "submit/analyses", to: "submit#analyses"
  get "submit/analysesCategory", to: "submit#analysesCategory"
  get "submit/pipelines", to: "submit#pipelines"
  get 'submit/job-query/', to: 'submit#query', as: 'query'
  get 'submit/job-query-demo', to: 'submit#query_demo', as: 'query-demo'

  get "submit/job-demo", to: "submit#demo"
  get 'submit/analysis/:id', to: 'submit#index', as: 'submit_analysis'
  get 'submit/pipeline/:id', to: 'submit#pipeline', as: 'submit_pipeline'
  post 'change_dark', to:'application#change_dark'

  post 'query-app-task', to: 'submit#query_app_task', format: 'json'
    post 'query-app-task-dummy', to: 'submit#query_app_task_dummy'
  post 'query-demo-tasks', to: 'submit#query_demo_tasks', format: 'json'
  post 'submit-app-task', to: 'submit#submit_app_task', format: 'json'
  post 'query-demo-task', to: 'submit#query_demo_task', format: 'json'
  post 'query-all-tasks', to: 'submit#query_all', format: 'json'
  post 'remove-task', to: 'submit#remove_task', format: 'json'

  # get "debug", to: "submit#query_app_task_test"
  # post 'query_app_task_dummy', to: 'submit#query_app_task_dummy'
  # post 'submit_app_task_dummy', to: 'submit#submit_app_task_dummy'
  # post 'submit-app-task', to: 'submit#submit_app_task', format: 'json'
  # post 'submit-app-task-dummy', to: 'submit#submit_app_task_dummy', format: 'json'

  # admin
  get '/admin', to: 'admin#index', as: "admin_index"
  post "admin/modify_sample_metadata" => "admin#modify_sample_metadata", :as => "admin/modify_sample_metadata"
  post "admin/modify_sample_inf" => "admin#modify_sample_inf", :as => "admin/modify_sample_inf"
  post "admin/update_samples_num_table_and_reprocessedColumns" => "admin#update_samples_num_table_and_reprocessedColumns", :as => "admin/update_samples_num_table_and_reprocessedColumns"
  post "admin/make_analysis_cancer_files" => "admin#make_analysis_cancer_files", :as => "admin/make_analysis_cancer_files"
  post "admin/make_subtype_cancer_files" => "admin#make_subtype_cancer_files", :as => "admin/make_subtype_cancer_files"
  post "admin/update_columns" => "admin#update_columns", :as => "admin/update_columns"
  post "admin/update_files" => "admin#update_files", :as =>"admin/update_files"
  post "admin/update_columns_cancer" => "admin#update_columns_cancer", :as => "admin/update_columns_cancer"

  post "admin/modify_viz" => "admin#modify_viz", :as => "admin/modify_viz"
  post "admin/modify_ana_cate" => "admin#modify_ana_cate", :as => "admin/modify_ana_cate"
  post "admin/modify_ana" => "admin#modify_ana", :as => "admin/modify_ana"
  post "admin/modify_viz_source" => "admin#modify_viz_source", :as => "admin/modify_viz_source"
  post "admin/add_img" => "admin#add_img", :as => "admin/add_img"
  post "admin/delete_samples" => "admin#delete_samples", :as => "admin/delete_samples"
  post "admin/update_all_samples" => "admin#update_all_samples", :as => "admin/update_all_samples"
  post "admin/update_all_organs" => "admin#update_all_organs", :as => "admin/update_all_organs"
  post "admin/update_all_cancers" => "admin#update_all_cancers", :as => "admin/update_all_cancers"
  post "admin/update_all_sections" => "admin#update_all_sections", :as => "admin/update_all_sections"
  post "admin/update_all_slices" => "admin#update_all_slices", :as => "admin/update_all_slices"
  post "admin/update_all_species" => "admin#update_all_species", :as => "admin/update_all_species"
  post "admin/update_all_tissues" => "admin#update_all_tissues", :as => "admin/update_all_tissues"
  post "admin/update_all_diseases" => "admin#update_all_diseases", :as => "admin/update_all_diseases"

  post "admin/update_gene_number" => "admin#update_gene_number", :as => "admin/update_gene_number"



  namespace :admin do
    post :update_analysis_category_position, to: 'analysis_categories#update_position'
    resources :analysis_categories, except: :show do
      post :update_position, to: 'analyses#update_position', as: 'update_analysis_position'
      resources :analyses, expect: %i[index show]
    end
    get 'analyses', to: 'analyses#index'
    resources :visualizers
    resources :analysis_pipelines
    resources :tasks, except: :new
    post "clear_outputs", to:"tasks#clear_outputs", as: "clear_outputs"
    post "set_demo_task", to:"tasks#set_demo_task", as: "set_demo_task"
    resources :file_keys, except: :show
    resources :tabix_apis, except: :show
  end

  # serve files
  match 'data/uploads/*path', to: 'raw_files#uploads', as: 'get_uploads', via: :get
  match 'data/demo/*path', to: 'raw_files#demo', as: 'get_demo', via: :get
  match 'data/outputs/*path', to: 'raw_files#outputs', as: 'get_outputs', via: :get
  match 'data/static_viz_data/*path', to: 'raw_files#viz_file', via: :get
  match 'public/data/*path', to: 'raw_files#public_file', via: :get
  match 'public/data/sample_plot/*path', to: 'raw_files#viz_inf_file', via: :get
  get "/database/refreshSelector", to: 'database#refreshSelector'

  post 'query-deepomics', to: 'submit#query_deepomics', format: 'json'
  post 'task-details', to: 'submit#task_details', format: 'json'



end

app/models/tissue.rb
class Tissue < ApplicationRecord
    validates :tissue_name, presence: true, uniqueness: { 
        message: ->(object, data) do
          "tissue #{data[:value]} already exists. "
        end
      }, on: :create
    
      def self.import(file)
          CSV.foreach(file.path, headers: true, encoding: 'bom|utf-8') do |row|
          tissue = Tissue.find_by(tissue_name: row['tissue_name']) || new
          tissue.attributes = row.to_hash.slice(*column_names)
  
          tissue.save!
          end
      end
end

app/controllers/tissues_controller.rb
class TissuesController < ApplicationController
    def index
    end

    def show
        @vis = ['id', 'section_name', 'sample_name', 'project_name', 'c_tissue_source',"tissue_name", 'c_tissue_type', "c_storage_type","c_metastasis"]

        @user = User.find(session[:user_id])
        @tissue = Tissue.find(params[:id])
        @attrs = Tissue.column_names
        @section_attrs = Section.column_names
        # @projects = @cancer.projects
        @invis = []
        @section_attrs.each_with_index do |attr, index|
            if !@vis.include?(attr)
                @invis.push(index+1)
            end
        end
        gon.push invis: @invis
        
        id = session[:user_id]
        @user = User.find(id) 
        @datasets = @user.datasets
        respond_to do |format|
            format.html
            # format.csv { send_data @cancer.projects.to_csv }
            format.json { render json: SectionDatatable.new(view_context, 'tissue', @tissue.tissue_name) }
        end
    end
end

app/helpers/tissues_helper.rb
module TissuesHelper
end

app/views/tissues/show.html.erb
<% content_for:head do%>

  
  <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/fixedcolumns/3.3.2/js/dataTables.fixedColumns.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.1/css/select.dataTables.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedcolumns/3.3.2/css/fixedColumns.dataTables.min.css">
  <%= javascript_pack_tag "datatable" %>
<%end%>

<% content_for :title, 'Tissue '+ @tissue.tissue_name %>

<div class="container">
  <div class='d-flex' >
    
    <h1 class = "mt-5">
      Species Information
    </h1>
  </div>
  <br>
  <%#= link_to 'Edit', edit_project_path(@project) %> 
  <%# <button class = 'btn btn-secondary'><%= link_to 'Back', cancers_path %></button>


  <br />

  <h2 class = "mt-3">Sections Information</h2>
  <div id="db-toolbar">
    <div class="db-tool-nav">
      <div class="btn btn-outline-dark" data-toggle="collapse" data-target="#hidden_helper" aria-expanded="true" aria-controls="hidden_helper"> 
          Filter Columns <i class="fas fa-caret-down"></i>
      </div>
      <div class="btn btn-outline-dark" data-toggle="collapse" data-target="#download_box" aria-expanded="true" aria-controls="download_box">
        Download Data <i class="fas fa-caret-down"></i>
      </div>
    </div>
    <div id='hidden_helper'  class="db-toolbox collapse p-2">
      <% i=2 %>
      <% @attrs.each do |attr| %>
        <% if attr != 'id'%>
          <% if !@vis.include? attr%>
            <button class="toggle-vis btn btn-outline-secondary" data-column='<%=i.to_s%>'> 
              <%= attr%>
            </button>
          <% end %>
          <%i += 1%>
        <%end%>
      <%end%>
    </div>
    <%= form_tag export_selected_projects_path(format: "csv"), multipart: true do %> 
      <div id="download_box" class="db-toolbox collapse" data-parent="#db-toolbar">
        <div class="form-group p-2">
          <%= button_tag :class => "s_table_sub btn btn-theme" do %>
            <i class='fas fa-check-circle'></i> Selected projects
          <%end%>
          <%= link_to cancer_path(format: "csv"), disabled: true, :class => "s_table_sub btn btn-pink float-right" do %>
            <i class='fas fa-download'></i> All projects
          <%end%>
        </div>
      </div>
    <%end%>
  </div>
  <br/>

  <%= form_tag export_selected_projects_path(format: "csv"), multipart: true do %>  
    <%= content_tag :table, role: :datatable, class: "display", id: "table_page", data: { url: tissue_path(format: :json)} do %>
      <thead>
            <th>
              <input type="checkbox" class="selectAll" name="selectAll" value="all">
            </th>
            <% @section_attrs.each do |attr| %>
              
              <th> <%= attr %> </th>
              
            <% end %>
            <th>details</th>
      </thead>
      <tbody>
      </tbody>
    <% end %>
    <%= hidden_field_tag 'tissue_id', @tissue.id %>
  <% end %>

</div>